---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: spark
  replicas: 1
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark
        image: bde2020/spark-master:2.4.5-hadoop2.7
        ports:
        - containerPort: 8080
